@isTest
public class BuilderControllerUnitTest {
	
	@TestSetup
	static void setup(){
		
	}


    @isTest
    public static void shouldSave() {

	}

    @isTest
    public static void shouldGetForm() {

    }
		
	@isTest
    public static void shouldUpdateForm() {

	}
	
	@isTest
    public static void shouldGetQuestions() {

    }
		
	@isTest
    public static void shouldSaveQuestion() {

	}
	
	@isTest
    public static void shouldSaveQuestionWithOptions() {

		// Form__c form = [SELECT Id FROM Form__c LIMIT 1];

		// List<Question__c> expectedQuestions = [SELECT Id FROM Question__c WHERE Type__c = 'Dropdown']; 

		// List<Question_Option__c> optionsCreate = TestDataFactory.generateQuestionOptions(expectedQuestions);

		// String sQuestion = JSON.serialize(expectedQuestions[0]); 

		// String sQuestionOptions = JSON.serialize(optionsCreate); 

		// Test.startTest();

        // Map<String, List<sObject>> options = BuilderController.saveQuestionWithOptions(sQuestion, sQuestionOptions);

		// Test.stopTest();

		// System.assertEquals(1, options.get('Options').size());
		
	}
	
	@isTest
    public static void shouldSaveQuestionWithCriteria() {

	}
	
	@isTest
    public static void shouldSaveRecordGroupFields() {

	}
	
	@isTest
    public static void shouldGetConnections() {

    }
		
	@isTest
    public static void shoulGetConnectionFieldMapping() {

	}
	
	@isTest
    public static void shoulSaveConnections() {

	}
	
	@isTest
    public static void shoulSaveActiveFieldConnections() {

	}
	
	@isTest
    public static void shoulDeletePageQuestions() {

	}
	
	@isTest
    public static void shoulDeleteQuestion() {

	}
	
	@isTest
    public static void shoulGetSObjectsAvailable() {

    }
		

}
