@isTest
public class FormSummaryControllerUnitTest {
	
	@TestSetup
	static void setup(){
		
	}

	@isTest
	public static void shouldCreateNewResponse() {

	}

	@isTest
	public static void shouldGetForm() {

	}

	@isTest
	public static void shouldGetFormResponses() {

	}

	@isTest
	public static void shouldDeleteFormResponse() {

	}

	@isTest
	public static void shouldDeleteForm() {

	}

	@isTest
	public static void shouldPublishForm() {

	}

	@isTest
	public static void shouldGetAnswerColumns() {

	}

}
