@isTest
public class ClarityFormBuilderTest {

    @testSetup
    public static void setup(){
    }

    @isTest
    public static void shouldSave() {

    }

    @isTest
    public static void shouldStartup() {

    }

    @isTest
    public static void shouldUpdateForm() {

    }

    @isTest
    public static void shouldGetDesigns() {

    }

    @isTest
    public static void shouldUpdateDesign() {

    }

    @isTest
    public static void shouldGetQuestions() {

    }

    @isTest
    public static void shouldSaveQuestionWithOptions() {

    }

    @isTest
    public static void shouldDeletePage() {

    }

    @isTest
    public static void shouldDeleteQuestion() {

    }

    @isTest
    public static void shouldGetQuestionDetails() {

    }

    @isTest
    public static void shouldSaveFlowDesign() {

    }

    @isTest
    public static void shouldSaveQuestionWithCriteria() {

    }

    @isTest
    public static void shouldGetSObjectsAvailable() {

    }

    @isTest
    public static void shouldCreateAssignment() {

    }

    @isTest
    public static void shouldGetAssignmentRules() {

    }

    @isTest
    public static void shouldSaveAssignmentRules() {

    }

    @isTest
    public static void shouldSaveRecordGroupFields() {

    }

    @isTest
    public static void shouldGetConnections() {

    }

    @isTest
    public static void shouldGetConnectionFieldMapping() {

    }

    @isTest
    public static void shouldSaveConnections() {

    }
    
    @isTest
    public static void shouldSaveActiveFieldConnections() {

    }

    @isTest
    public static void shouldGetUsers() {

    }

    @isTest
    public static void shouldUpdateStatus() {

    }
}
